src/Entity/Disponibilite.php
<?php

namespace App\Entity;

use App\Repository\DisponibiliteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DisponibiliteRepository::class)]
class Disponibilite
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $agent_id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $debut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fin = null;

    #[ORM\Column]
    private ?bool $all_day = null;

    #[ORM\Column(length: 7)]
    private ?string $background_color = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAgentId(): ?int
    {
        return $this->agent_id;
    }

    public function setAgentId(int $agent_id): static
    {
        $this->agent_id = $agent_id;

        return $this;
    }

    public function getDebut(): ?\DateTimeInterface
    {
        return $this->debut;
    }

    public function setDebut(\DateTimeInterface $debut): static
    {
        $this->debut = $debut;

        return $this;
    }

    public function getFin(): ?\DateTimeInterface
    {
        return $this->fin;
    }

    public function setFin(\DateTimeInterface $fin): static
    {
        $this->fin = $fin;

        return $this;
    }

    public function isAllDay(): ?bool
    {
        return $this->all_day;
    }

    public function setAllDay(bool $all_day): static
    {
        $this->all_day = $all_day;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): static
    {
        $this->background_color = $background_color;

        return $this;
    }
}

src/Form/DisponibiliteType.php
<?php

namespace App\Form;

use App\Entity\Disponibilite;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DisponibiliteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('debut',DateTimeType::class, [
                'date_widget' => 'single_text',
            ])
            ->add('fin',DateTimeType::class, [
                'date_widget' => 'single_text',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Disponibilite::class,
        ]);
    }
}

src/Controller/DisponibiliteController.php
<?php
namespace App\Controller;

use App\Entity\Disponibilite;
use App\Form\DisponibiliteType;
use App\Repository\DisponibiliteRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/disponibilite')]
class DisponibiliteController extends AbstractController
{
    #[Route('/', name: 'app_disponibilite_index', methods: ['GET'])]
    public function index(DisponibiliteRepository $disponibiliteRepository): Response
    {
        return $this->render('disponibilite/index.html.twig', [
            'disponibilites' => $disponibiliteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_disponibilite_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {
        $user = $this->getUser();
        $login = $user->getUserIdentifier();
        $utilisateur = $userRepository->findOneBy(['login' => $login]);

        $disponibilite = new Disponibilite();
        $form = $this->createForm(DisponibiliteType::class, $disponibilite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $disponibilite->setAgentId($utilisateur->getId());
            $disponibilite->setBackgroundColor('#5b0054');
            $entityManager->persist($disponibilite);
            $entityManager->flush();

            return $this->redirectToRoute('app_disponibilite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('disponibilite/new.html.twig', [
            'disponibilite' => $disponibilite,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_disponibilite_show', methods: ['GET'])]
    public function show(Disponibilite $disponibilite): Response
    {
        return $this->render('disponibilite/show.html.twig', [
            'disponibilite' => $disponibilite,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_disponibilite_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Disponibilite $disponibilite, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DisponibiliteType::class, $disponibilite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_disponibilite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('disponibilite/edit.html.twig', [
            'disponibilite' => $disponibilite,
            'form' => $form->createView(),
        ]);
    }



    #[Route('/delete-disponibilite/{id}', name: 'delete_disponibilite', methods: ['POST'])]
    public function delete(Request $request, Disponibilite $disponibilite, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($disponibilite);
        $entityManager->flush();

        return $this->json(['success' => true]);
    }
}

src/Controller/DisponibilitesController.php
<?php
namespace App\Controller;

use App\Entity\Disponibilite;
use App\Repository\DisponibiliteRepository;
use App\Repository\EvenementRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DisponibilitesController extends AbstractController
{
    #[Route('/disponibilites', name: 'app_disponibilites')]
    public function index(DisponibiliteRepository $disponibiliteRepository, EvenementRepository $evenementRepository, UserRepository $userRepository): Response
    {
        $user = $this->getUser();
        if (!$user) {
            throw $this->createAccessDeniedException('Vous n\'êtes pas authentifié.');
        }

        $login = $user->getUserIdentifier();
        $utilisateur = $userRepository->findOneBy(['login' => $login]);
        if (!$utilisateur) {
            throw $this->createNotFoundException('Utilisateur non trouvé.');
        }

        $disponibilites = $disponibiliteRepository->findByUser($utilisateur->getId());
        $evenements = $evenementRepository->findAll(); // Récupère tous les événements

        $dispos = array_map(function ($dispo) {
            return [
                'id' => $dispo->getId(),
                'title' => '- ' . $dispo->getFin()->format('H:i'),
                'start' => $dispo->getDebut()->format('Y-m-d H:i:s'),
                'end' => $dispo->getFin()->format('Y-m-d H:i:s'),
                'allDay' => $dispo->isAllDay(),
                'backgroundColor' => $dispo->getBackgroundColor(),
            ];
        }, $disponibilites);

        $evenementList = array_map(function ($evenement) {
            return [
                'id' => $evenement->getId(),
                'nom' => $evenement->getNom(),
                'datedebut' => $evenement->getDatedebut()->format('Y-m-d'),
                'datefin' => $evenement->getDatefin()->format('Y-m-d'),
                'couleur' => sprintf('#%06X', mt_rand(0, 0xFFFFFF)) // Génère une couleur aléatoire
            ];
        }, $evenements);

        $data = json_encode($dispos);
        $evenementsJson = json_encode($evenementList);

        return $this->render('disponibilites/index.html.twig', [
            'data' => $data,
            'evenements' => $evenementsJson
        ]);
    }





    #[Route('/add-disponibilite', name: 'add_disponibilite', methods: ['POST'])]
    public function addDisponibilite(Request $request, EntityManagerInterface $entityManager, UserRepository $userRepository): \Symfony\Component\HttpFoundation\JsonResponse
    {
        $user = $this->getUser();
        $login = $user->getUserIdentifier();
        $utilisateur = $userRepository->findOneBy(['login' => $login]);
        $data = json_decode($request->getContent(), true);

        $disponibilite = new Disponibilite();
        $disponibilite->setAgentId($utilisateur->getId());
        $disponibilite->setDebut(new \DateTime($data['debut']));
        $disponibilite->setFin(new \DateTime($data['fin']));
        $disponibilite->setAllDay(false);
        $disponibilite->setBackgroundColor('#5b0054');
        $entityManager->persist($disponibilite);
        $entityManager->flush();

        return $this->json(['success' => true]);
    }

    #[Route('/disponibilites/toutes', name: 'app_disponibilites_toutes')]
    public function viewAll(DisponibiliteRepository $disponibiliteRepository, UserRepository $userRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $evenements = $disponibiliteRepository->findAll();
        $dispos = [];

        foreach ($evenements as $dispo) {
            $agent = $userRepository->find($dispo->getAgentId());

            $dispos[] = [
                'id' => $dispo->getId(),
                'title' => $agent->getNom() . ' - ' . $dispo->getDebut()->format('H:i') . ' - ' . $dispo->getFin()->format('H:i'),
                'start' => $dispo->getDebut()->format('Y-m-d H:i:s'),
                'end' => $dispo->getFin()->format('Y-m-d H:i:s'),
                'allDay' => $dispo->isAllDay(),
                'backgroundColor' => $dispo->getBackgroundColor(),
            ];
        }

        $data = json_encode($dispos);

        return $this->render('disponibilites/toutes.html.twig', ['data' => $data]);
    }

    #[Route('/disponibilites/date/{date}', name: 'disponibilites_par_date')]
    public function disponibilitesParDate($date, DisponibiliteRepository $disponibiliteRepository, UserRepository $userRepository): Response
    {
        try {
            $debut = new \DateTime($date . ' 00:00:00');
            $fin = new \DateTime($date . ' 23:59:59');

            $disponibilites = $disponibiliteRepository->findByDateRange($debut, $fin);

            $data = array_map(function ($dispo) use ($userRepository) {
                $agent = $userRepository->find($dispo->getAgentId());
                return [
                    'agent' => $agent->getNom(),
                    'agent_id' => $agent->getId(),
                    'debut' => $dispo->getDebut()->format('H:i'),
                    'fin' => $dispo->getFin()->format('H:i')
                ];
            }, $disponibilites);

            return $this->json($data);
        } catch (\Exception $e) {
            return $this->json(['error' => 'Une erreur est survenue.'], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }



}

templates/disponibilite/_delete_form.html.twig
<form method="post" action="{{ path('app_disponibilite_delete', {'id': disponibilite.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ disponibilite.id) }}">
    <button class="btn">Delete</button>
</form>

templates/disponibilite/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/disponibilite/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Disponibilite{% endblock %}

{% block body %}
    <h1>Edit Disponibilite</h1>

    {{ include('disponibilite/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_disponibilite_index') }}">back to list</a>

    {{ include('disponibilite/_delete_form.html.twig') }}
{% endblock %}

templates/disponibilite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Disponibilite index{% endblock %}

{% block body %}
    <h1>Disponibilite index</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Agent_id</th>
            <th>Debut</th>
            <th>Fin</th>
            <th>All_day</th>
            <th>Background_color</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for disponibilite in disponibilites %}
            <tr>
                <td>{{ disponibilite.id }}</td>
                <td>{{ disponibilite.agentId }}</td>
                <td>{{ disponibilite.debut ? disponibilite.debut|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ disponibilite.fin ? disponibilite.fin|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ disponibilite.allDay ? 'Yes' : 'No' }}</td>
                <td>{{ disponibilite.backgroundColor }}</td>
                <td>
                    <a href="{{ path('app_disponibilite_show', {'id': disponibilite.id}) }}">show</a>
                    <a href="{{ path('app_disponibilite_edit', {'id': disponibilite.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_disponibilite_new') }}">Create new</a>
{% endblock %}

templates/disponibilite/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Disponibilite{% endblock %}

{% block body %}
    <h1>Create new Disponibilite</h1>

    {{ include('disponibilite/_form.html.twig') }}

    <a href="{{ path('app_disponibilite_index') }}">back to list</a>
{% endblock %}

templates/disponibilite/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Disponibilite{% endblock %}

{% block body %}
    <h1>Disponibilite</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ disponibilite.id }}</td>
            </tr>
            <tr>
                <th>Agent_id</th>
                <td>{{ disponibilite.agentId }}</td>
            </tr>
            <tr>
                <th>Debut</th>
                <td>{{ disponibilite.debut ? disponibilite.debut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Fin</th>
                <td>{{ disponibilite.fin ? disponibilite.fin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>All_day</th>
                <td>{{ disponibilite.allDay ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Background_color</th>
                <td>{{ disponibilite.backgroundColor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_disponibilite_index') }}">back to list</a>

    <a href="{{ path('app_disponibilite_edit', {'id': disponibilite.id}) }}">edit</a>

    {{ include('disponibilite/_delete_form.html.twig') }}
{% endblock %}